# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b567c1e647a916d56a7144f8b2192f4d5d0111633010f08fa5568921226625b1b1b470a9db32c21334451f546133ee885cf14f8b51c7aba099a03a6392f405f4

test:
  secret_key_base: f8e988e58138c453c5a8a64858966135b4bfec724397e68660f438b6b05531d7de53f825e9875204fbf243540a001b378eb4f7469cabe0d556e9eb604cc802f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
